version: '3.7'

services:
  develop:
    container_name: deploy-vps-develop
    image: waziat/deploy-vps:develop
    environment:
      - NODE_ENV=development
    ports: 
      - 3001:3000
    restart: always
    networks:
      - liburanterus-microservices-networks
    working_dir: /user/app
  
  testing:
    container_name: deploy-vps-testing
    image: waziat/deploy-vps:testing
    # build: 
    #   context: .
    #   dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=testing
    ports: 
      - 3002:3000
    restart: always
    networks:
      - liburanterus-microservices-networks
    working_dir: /user/app

  staging:
    container_name: deploy-vps-staging
    image: waziat/deploy-vps:staging
    environment:
      - NODE_ENV=staging
    ports: 
      - 3003:3000
    restart: always
    networks:
      - liburanterus-microservices-networks
    working_dir: /user/app
  
  production:
    container_name: deploy-vps-production
    image: waziat/deploy-vps:production
    environment:
      - NODE_ENV=production
    ports: 
      - 3004:3000
    restart: always
    networks:
      - liburanterus-microservices-networks
    working_dir: /user/app

networks:
  liburanterus-microservices-networks: 
    name: 'liburanterus-microservices-networks'
