version: '3.7'

services:
  develop:
    container_name: deploy-vps-develop
    image: waziat/deploy-vps:develop
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    ports: 
      - 3001:3000
    restart: always
    networks:
      - liburanterus-microservices-networks
    working_dir: /user/app
  
  staging:
    container_name: deploy-vps-staging
    image: waziat/deploy-vps:staging
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    ports: 
      - 3002:3000
    restart: always
    networks:
      - liburanterus-microservices-networks
    working_dir: /user/app

networks:
  liburanterus-microservices-networks: 
    name: 'liburanterus-microservices-networks'
