name: Deploy to VPS

on:
  pull_request:
    branches: 
    - develop
    - testing
    - staging
    - production

env: 
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_IMAGE: deploy-vps
  VPS_HOST: ${{ secrets.VPS_HOST }}
  VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}


jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install

    - name: Run linting and unit tests
      run: npm test

    - name: Build React app
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        IMAGE_TAG=${{github.event.pull_request.base.ref}}
        if [ -z "$IMAGE_TAG" ]; then
          IMAGE_TAG=latest
        fi
        echo "IMAGE_TAG: $IMAGE_TAG"

        docker build . --file Dockerfile --tag $DOCKER_USERNAME/$DOCKER_IMAGE:$IMAGE_TAG

    - name: Login to Docker Hub
      run: |
        echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
    
    - name: Push Image to Docker Hub
      run: |
        IMAGE_TAG=${{github.event.pull_request.base.ref}}
        if [ -z "$IMAGE_TAG" ]; then
          IMAGE_TAG=latest
        fi
        echo "IMAGE_TAG: $IMAGE_TAG"

        docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$IMAGE_TAG
    
    - name: Transfer compose file to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        source: docker-compose.yml
        target: /var/www/app/$DOCKER_IMAGE
        script: 
          whoami
          echo ${{ secrets.PRIVATE_KEY }}

    - name: SSH to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /var/www/app/$DOCKER_IMAGE
          docker-compose pull
          docker-compose down ${{github.event.pull_request.base.ref}}
          docker-compose up ${{github.event.pull_request.base.ref}} -d
